#pragma once

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#ifndef RGB_MATRIX_MAXIMUM_BRIGHTNESS
# define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#endif

#define COOKYT_DEFAULT_HSV HSV_AZURE
#define RGB_MATRIX_DEFAULT_HUE 132
#define RGB_MATRIX_DEFAULT_SAT 102
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS

#define COOKYT_ALTERNATE_HSV HSV_CHARTREUSE
