OLED_ENABLE = yes
VIA_ENABLE = yes
WPM_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no

COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes

COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no

# CONVERT_TO = bit_c_pro
